name: buf
on:
  push:
    branches: ["main"]
  workflow_dispatch: {} # support manual runs
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@latest
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-push-action@latest
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}